
BINARIES = tcp-server tcp-client

all: $(BINARIES)

clean:
	rm -f $(BINARIES)

tcp-server: tcp-server.c
	gcc -o tcp-server tcp-server.c -Wall

tcp-client: tcp-client.c
	gcc -o tcp-client tcp-client.c -Wall




